name: ReaPack Indexer

on:
  push:
    branches: [ master, main ]

permissions:
  contents: write 

jobs:
  reapack-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Pandoc)
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install reapack-index
        run: gem install reapack-index

      - name: Run reapack-index
        run: reapack-index --name "ZSReaScripts" --no-commit --no-warnings

      # 3. Automatically push the generated index.xml to your repo
      - name: Push generated index
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate ReaPack index.xml"
